export { AnalyticsPage } from './analytics/Analytics'
export { DashboardPage } from './dashboard/Dashboard'
export { DistrictDetailsPage, DistrictListPage } from './district'
export { ExplainabilityPage } from './explainability/Explainability'
export { GeospatialPage } from './geospatial/Geospatial'
export { LoginPage } from './auth/Login'
export { NotFoundPage } from './notfound/NotFound'
export { ReportsPage } from './reports/Reports'
export { SettingsPage } from './settings/Settings'
