"""
====================================================
Saved Report Model
====================================================
Stores user-generated reports with metadata.
====================================================
"""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from sqlalchemy import (
    BigInteger,
    DateTime,
    Enum as SQLEnum,
    ForeignKey,
    Index,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.models.user import User
from app.database.session import Base


class ReportFormat(str, Enum):
    """Report output format."""
    CSV = "csv"
    PDF = "pdf"
    GEOJSON = "geojson"
    JSON = "json"


class ReportStatus(str, Enum):
    """Report generation status."""
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    EXPIRED = "expired"


class ReportType(str, Enum):
    """Type of report."""
    DASHBOARD_SUMMARY = "dashboard_summary"
    RISK_RANKING = "risk_ranking"
    HOTSPOT_ANALYSIS = "hotspot_analysis"
    DISTRICT_DEEP_DIVE = "district_deep_dive"
    ANALYTICS_REPORT = "analytics_report"
    EXPLAINABILITY = "explainability"
    CUSTOM = "custom"


class SavedReport(Base):
    """Saved reports generated by users."""

    __tablename__ = "saved_reports"
    __table_args__ = (
        Index("ix_saved_reports_user_id", "user_id"),
        Index("ix_saved_reports_status", "status"),
        Index("ix_saved_reports_type", "report_type"),
        Index("ix_saved_reports_created_at", "created_at"),
    )

    # Primary key
    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
    )

    # Foreign keys
    user_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Report metadata
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    report_type: Mapped[ReportType] = mapped_column(
        SQLEnum(ReportType, name="report_type"),
        nullable=False,
    )
    format: Mapped[ReportFormat] = mapped_column(
        SQLEnum(ReportFormat, name="report_format"),
        nullable=False,
    )
    status: Mapped[ReportStatus] = mapped_column(
        SQLEnum(ReportStatus, name="report_status"),
        default=ReportStatus.PENDING,
        nullable=False,
    )

    # Filters & parameters
    filters: Mapped[Optional[dict]] = mapped_column(JSONB, default=dict)
    parameters: Mapped[Optional[dict]] = mapped_column(JSONB, default=dict)

    # File info
    file_path: Mapped[Optional[str]] = mapped_column(String(1000))
    file_size: Mapped[Optional[int]] = mapped_column(BigInteger)
    file_hash: Mapped[Optional[str]] = mapped_column(String(64))
    download_count: Mapped[int] = mapped_column(BigInteger, default=0, nullable=False)

    # Error tracking
    error_message: Mapped[Optional[str]] = mapped_column(Text)
    retry_count: Mapped[int] = mapped_column(BigInteger, default=0, nullable=False)

    # Timing
    generation_started_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    generation_completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    expires_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))

    # Audit
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="saved_reports")

    def __repr__(self) -> str:
        return f"<SavedReport {self.title} ({self.format.value})>"
